package com.easygql.component;

import com.easygql.exception.InternalServerException;
import com.easygql.util.DataSourceInfo;
import lombok.extern.slf4j.Slf4j;
import org.springframework.core.env.Environment;
import org.springframework.core.io.support.PropertiesLoaderUtils;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.text.DecimalFormat;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.Optional;
import java.util.Properties;

/**
 * @author guofen
 * @date 2019-10-27 16:41
 */

@Component
@Slf4j
public class
ConfigurationProperties  {
    private static volatile ConfigurationProperties instance=null;
    private static final  String property = "application.properties";
    private Environment env;
    public final String SCHEMA_DATABASE_KIND;
    public final String ROLE_IN_USER_FIELDNAME;
    public final String POSTGRES_IP;
    public final Integer POSTGRES_PORT;
    public final String POSTGRES_DATABASENAME;
    public final String POSTGRES_USER;
    public final String POSTGRES_PASS;
    public final Integer POSTGRES_MAX_CONNECTIONS;
    public final Integer POSTGRES_MAX_IDLE_CONNECTIONS;
    public final String SCHEMAID_DEFAULT;
    public final DateTimeFormatter DEFAULT_DATETIME_FORMAT;
    public final DateTimeFormatter DEFAULT_TIME_FORMAT;
    public final DateTimeFormatter DEFAULT_DATE_FORMAT;
    public final DataSourceInfo POSTGRES_DATASOURCE_INSTANCE;
    public final Integer GRAPHQL_RECURSIVE_DEEPTH;
    public final Locale GRAPHQL_LANG;
    public static final String EMPTY_STRING="";
    public static final String GRAPHQL_ROLE_ID_POSTFIX="_role";
    public static final String POSTGRES_DEFAULT_DATABSENAME = "postgres";
    public static final String GRAPHQL_USERNAME_FIELD = "username";
    public static final String GRAPHQL_PASSWORD_FIELD = "password";
    public static final String GRAPHQL_OLD_PASSWORD_FIELD = "oldPassword";
    public static final String GRAPHQL_NEW_PASSWORD_FIELD = "newPassword";
    public static final String DATABASE_KIND_POSTGRES = "PostgreSQL";
    public static final String DATABASE_KIND_RETHINKDB = "RethinkDB";
    public static final String DATABASE_KIND_MONGODB = "MongoDB";
    public static final String DATABASE_KIND_MYSQL = "MySQL";
    public static final String POSTGRES_COLUMNNAME_PREFIX = "f_";
    public static final String POSTGRES_DATABASENAME_PREFIX = "d_";
    public static final String POSTGRES_TABLENAME_PREFIX = "t_";
    public static final String POSTGRES_ID_FIELD = "id";
    public static final String POSTGRES_TRIGGERHIS="trigger_his";
    public static final String GRAPHQL_FIELDS_FIELDNAME="fields";
    public static final String GRAPHQL_TYPE_FIELDNAME="type";
    public static final String GRAPHQL_NOTNULL_FIELDNAME="notnull";
    public static final String GRAPHQL_ISLIST_FIELDNAME="islist";
    public static final String GRAPHQL_DEFAULT_FIELDNAME="default";
    public static final String GRAPHQL_IS_SYSTEMFIELD_FIELDNAME="issystemfield";
    public static final String GRAPHQL_IS_UNIQUE_FIELDNAME="isunique";
    public static final String GRAPHQL_ROLENAME_FIELDNAME="rolename";
    public static final String GRAPHQL_DESCRIPTION_FIELDNAME="description";
    public static final String GRAPHQL_ENUMID_FIELDNAME="enumid";
    public static final String GRAPHQL_IS_SYSTEMDEFINED_FIELDNAME="isSystemDefined";
    public static final String GRAPHQL_TRIGGERS_FIELDNAME="triggers";
    public static final String GRAPHQL_CONTENTTYPE_ID_FIELDNAME="contentTypeId";
    public static final String POSTGRES_FROM_COLUMNNAME="f_from";
    public static final String POSTGRES_TO_COLUMNNAME="f_to";
    public static final String GRAPHQL_CONTENTTYPE_FIELDNAME="contentType";
    public static final String GRAPHQL_FIELDS_ID_FIELDNAME="fields_id";
    public static final String GRAPHQL_POSTGRESQL_ID="postgresql_id";
    public static final String GRAPHQL_RETHINKDB_ID="rethinkdb_id";
    public static final String GRAPHQL_MONGODB_ID="mongodb_id";
    public static final String GRAPHQL_MYSQL_ID="mydsql_id";
    public static final String GRAPHQL_INTTYPE_ID="inttype_id";
    public static final String GRAPHQL_FLOATTYPE_ID="floattype_id";
    public static final String GRAPHQL_BOOLEAN_TYPE_ID="booleantype_id";
    public static final String GRAPHQL_STRING_TYPE_ID="stringtype_id";
    public static final String GRAPHQL_ID_TYPE_ID="id_id";
    public static final String GRAPHQL_SHORT_TYPE_ID="short_id";
    public static final String GRAPHQL_LONG_TYPE_ID="long_id";
    public static final String GRAPHQL_BYTE_TYPE_ID="byte_id";
    public static final String GRAPHQL_BIGINTEGER_TYPE_ID="biginteger_id";
    public static final String GRAPHQL_BIGDECIMAL_TYPE_ID="bigdecimal_id";
    public static final String GRAPHQL_CHAR_TYPE_ID="char_id";
    public static final String GRAPHQL_object_TYPE_ID="object_id";
    public static final String GRAPHQL_JSON_TYPE_ID="json_id";
    public static final String GRAPHQL_DATE_TYPE_ID="date_id";
    public static final String GRAPHQL_DATETIME_TYPE_ID="datetime_id";
    public static final String GRAPHQL_TIME_TYPE_ID="time_id";
    public static final String GRAPHQL_EMAIL_TYPE_ID="email_id";
    public static final String GRAPHQL_LASTUPDATE_TYPE_ID="lastupdate_id";
    public static final String GRAPHQL_URL_TYPE_ID = "url_id";
    public static final String GRAPHQL_CREATEDAT_TYPE_ID="createdat_id";
    public static final String GRAPHQL_ID_TYPENAME = "ID";
    public static final String GRAPHQL_ID_FIELDNAME = "id";
    public static final String GRAPHQL_TYPE_ID_FIELDNAME="typeid";
    public static final String GRAPHQL_ONE2ONE_ID="one2one_id";
    public static final String GRAPHQL_ONE2ONE_NAME="One2One";
    public static final String GRAPHQL_ONE2MANY_ID="one2many_id";
    public static final String GRAPHQL_ONE2MANY_NAME="One2Many";
    public static final String GRAPHQL_MANY2ONE_ID="many2one_id";
    public static final String GRAPHQL_MANY2ONE_NAME="Many2One";
    public static final String GRAPHQL_MANY2MANY_ID="many2many_id";
    public static final String GRAPHQL_MANY2MANY_NAME="Many2Many";
    public static final String GRAPHQL_RELATIONKIND_ID="relationkind_id";
    public static final String GRAPHQL_RELATIONKIND_ENUM_NAME="RelationKind";
    public static final String GRAPHQL_ENUMRELATION_ID="enumrelation_id";
    public static final String GRAPHQL_ENUMRELATION_NAME="EnumRelation";
    public static final String GRAPHQL_OBJECTRELATION_ID="objectrelation_id";
    public static final String GRAPHQL_OBJECTRELATION_NAME="ObjectRelation";
    public static final String GRAPHQL_RELATIONTYPE_ID="relationtype_id";
    public static final String GRAPHQL_REFERENCERELATION_ID="referencerelation_id";
    public static final String GRAPHQL_REFERENCERELATION_NAME="ReferenceRelation";
    public static final String GRAPHQL_SCALARFIELD_FIELDNAME="scalarfields";
    public static final String GRAPHQL_ENUMFIELD_FIELDNAME="enumfields";
    public static final String GRAPHQL_ENUMFIELD_TYPENAME="EnumField";
    public static final String GRAPHQL_RELATIONFIELD_TYPENAME="RelationField";
    public static final String GRAPHQL_FROMRELATIONFIELD_FIELDNAME="fromrelations";
    public static final String GRAPHQL_UNIQUE_CONSTRAINT_FIELDNAME="unique_constraints";
    public static final String GRAPHQL_TORELATIONFIELD_FIELDNAME="torelations";
    public static final String GRAPHQL_FROMOBJECT_FIELDNAME= "fromObject";
    public static final String GRAPHQL_FROMFIELD_FIELDNAME="fromField";
    public static final String GRAPHQL_TOOBJECT_FIELDNAME="toObject";
    public static final String GRAPHQL_TOFIELD_FIELDNAME="toField";
    public static final String GRAPHQL_RELATIONTYPE_NAME="RelationType";
    public static final String GRAPHQL_ENUMELEMENT_ID="enumelement_id";
    public static final String GRAPHQL_ENUMELEMENT_NAME="EnumElement";
    public static final String GRAPHQL_ENUM_FIELDNAME="enumtype";
    public static final String GRAPHQL_ROLE_DEFAULT_ID="easygql_role";
    public static final String GRAPHQL_ROLE_ENUMNAME="Role";
    public static final String GRAPHQL_SCALAR_ENUM_ID="scalartype_id";
    public static final String GRAPHQL_SCALAR_ENUM_NAME="ScalarType";
    public static final String GRAPHQL_FIELDKIND_ENUMNAME="FieldKind";
    public static final String GRAPHQL_FIELDKIND_FIELDNAME="fieldKind";
    public static final String GRAPHQL_DEFAULTVALUE_FIELDNAME="defaultvalue";
    public static final String GRAPHQL_ENUMMETADATA="enumtype";
    public static final String GRAPHQL_QUERY_TYPENAME="query";
    public static final String GRAPHQL_QUERYAPI_FIELDNAME="query";
    public static final String GRAPHQL_MUTATIONAPI_FIELDNAME ="mutation";
    public static final String GRAPHQL_SUBSCRIPTIONAPI_FIELDNAME="subscription";
    public static final String GRAPHQL_MUTATION_TYPENAME="mutation";
    public static final String GRAPHQL_SUBSCRIPTION_TYPENAME="Listener";
    public static final String GRAPHQL_DATABASEKIND_DEFAULT_ID="databasekind_id";
    public static final String GRAPHQL_DATABASEKIND_ENUMNAME="DatabaseKind";
    public static final String GRAPHQL_CREATEDAT_TYPENAME = "CreatedAt";
    public static final String GRAPHQL_DATABASEKIND_TYPENAME = "DataBaseKind";
    public static final String GRAPHQL_STRING_TYPENAME = "String";
    public static final String GRAPHQL_TYPEKIND_ENUM="EnumType";
    public static final String GRAPHQL_TYPEKIND_RELATION="RelationType";
    public static final String GRAPHQL_TYPEKIND_SCALAR="ScalarType";
    public static final String GRAPHQL_CHAR_TYPENAME = "Char";
    public static final String GRAPHQL_OBJECT_TYPENAME = "Object";
    public static final String GRAPHQL_JSON_TYPENAME = "JSON";
    public static final String GRAPHQL_DATE_TYPENAME = "Date";
    public static final String GRAPHQL_DATETIME_TYPENAME = "DateTime";
    public static final String GRAPHQL_TIME_TYPENAME = "Time";
    public static final String GRAPHQL_BIGDECIMAL_TYPENAME = "BigDecimal";
    public static final String GRAPHQL_BIGINTEGER_TYPENAME = "BigInteger";
    public static final String GRAPHQL_LASTUPDATE_TYPENAME = "LastUpdate";
    public static final String GRAPHQL_TABLENAME_PREFIX="t_";
    public static final String GRAPHQL_FLOAT_TYPENAME = "Float";
    public static final String GRAPHQL_SHORT_TYPENAME = "Short";
    public static final String GRAPHQL_LONG_TYPENAME = "Long";
    public static final String GRAPHQL_URL_TYPENAME="URL";
    public static final String GRAPHQL_INT_TYPENAME = "Int";
    public static final String GRAPHQL_BOOLEAN_TYPENAME = "Boolean";
    public static final String GRAPHQL_EMAIL_TYPENAME = "Email";
    public static final String GRAPHQL_BYTE_TYPENAME = "Byte";
    public static final String GRAPHQL_AFFECTEDROW_FIELDNAME = "affectedRows";
    public static final String GRAPHQL_SQL_FIELDNAME="sql";
    public static final String GRAPHQL_TUPLE_FIELDNAME="tuple";
    public static final String GRAPHQL_RESET_FIELDNAME="reset";
    public static final String GRAPHQL_IDLIST_FIELDNAME = "id_list";
    public static final String GRAPHQL_ROLE_TYPENAME = "Role";
    public static final String GRAPHQL_DISABLED_API_FIELDNAME="disabledAPIs";
    public static final String GRAPHQL_API_CONSTRAINT_FIELDNAME="apiConstraints";
    public static final String GRAPHQL_DATABASEKIND_FIELDNAME="databaseKind";
    public static final String GRAPHQL_DATASOURCE_TYPENAME="DataSource";
    public static final String GRAPHQL_DATASOURCE_FIELDNAME="datasource";
    public static final String GRAPHQL_USER_TYPENAME = "User";
    public static final String GRAPHQL_ROLE_FIELDNAME = "role";
    public static final String GRAPHQL_ROLES_FIELDNAME="roles";
    public static final String GRAPHQL_UNUPDATEBLE_ROLES_FIELDNAME="unupdatableRoles";
    public static final String GRAPHQL_UNDELETABLE_ROLES_FIELDNAME="undeletableRoles";
    public static final String GRAPHQL_INVISIBLE_ROLES_FIELDNAME="invisibleRoles";
    public static final String GRAPHQL_UNMODIFIABLE_ROLES_FIELDNAME ="unmodifiableRoles";
    public static final String GRAPHQL_RELATIONTYPE_FIELDNAME="relationType";
    public static final String GRAPHQL_IF_CASCADE_FIELDNAME="ifCascade";
    public static final String GRAPHQL_FILTER_AND_OPERATOR = "and";
    public static final String GRAPHQL_FILTER_OR_OPERATOR = "or";
    public static final String GRAPHQL_FILTER_NOT_OPERATOR = "not";
    public static final String GRAPHQL_FILTER_FILTER_OPERATOR = "filter";
    public static final String GRAPHQL_FILTER_CONTAIN_OPERATOR="contains";
    public static final String GRAPHQL_FILTER_FIELDCONTAIN_OPERATOR = "fieldContains";
    public static final String GRAPHQL_FILTER_EQ_OPERATOR = "eq";
    public static final String GRAPHQL_FILTER_NE_OPERATOR = "ne";
    public static final String GRAPHQL_FILTER_GT_OPERATOR = "gt";
    public static final String GRAPHQL_FILTER_GE_OPERATOR = "ge";
    public static final String GRAPHQL_FILTER_LT_OPERATOR = "lt";
    public static final String GRAPHQL_FILTER_LE_OPERATOR = "le";
    public static final String GRAPHQL_SESSIONID_FIELDNAME="sessionid";
    public static final String GRAPHQL_PACKAGENAME_FIELDNAME="package_name";
    public static final String GRAPHQL_PROTOCOL_FIELDNAME="protocol";
    public static final String GRAPHQL_FILTER_MATCH_OPERATOR = "match";
    public static final String GRAPHQL_FILTER_IN_OPERATOR = "in";
    public static final String GRAPHQL_MUTATION_OK_FIELDNAME="isok";
    public static final String GRAPHQL_MUTATION_DATA_FIELDNAME="mutationData";
    public static final String GRAPHQL_FILTER_NOTIN_OPERATOR = "notIn";
    public static final String GRAPHQL_FILTER_ISTRUE_OPERATOR = "isTrue";
    public static final String GRAPHQL_FILTER_HASONE_OPERATOR = "hasOne";
    public static final String GRAPHQL_STRINGFILTER_TYPENAME = "StringFilter";
    public static final String GRAPHQL_IDFILTER_TYPENAME = "IDFilter";
    public static final String GRAPHQL_INTFILTER_TYPENAME = "IntFilter";
    public static final String GRAPHQL_FLOATFILTER_TYPENAME="FloatFilter";
    public static final String GRAPHQL_SHORTFILTER_TYPENAME="ShortFilter";
    public static final String GRAPHQL_STRINGEQFILTER_TYPENAME="StringEQFilter";
    public static final String GRAPHQL_LONGFILTER_TYPENAME = "LongFilter";
    public static final String GRAPHQL_BIGDECIMALFILTER_TYPENAME = "BigDecimalFilter";
    public static final String GRAPHQL_BOOLFILTER_TYPENAME = "BoolFilter";
    public static final String GRAPHQL_ROWCONSTRAINT_CONST = "const";
    public static final String GRAPHQL_FIELDATTR_TYPENAME = "fieldattr";
    public static final String GRAPHQL_RELATIONTYPE_ENUMNAME = "RelationType";
    public static final String GRAPHQL_REMOTE_ENDPOINT_TYPENAME="remoteEndPoint";
    public static final String GRAPHQL_REMOTE_API_TYPENAME="remoteAPI";
    public static final String GRAPHQL_ENABLE_API_FIELDNAME="enabledAPIS";
    public static final String GRAPHQL_API_NAME_FIELDNAME="APIName";
    public static final String GRAPHQL_LOGIN_RESULT_TYPENAME = "LoginResult";
    public static final String GRAPHQL_LOGIN_RESULT_FIELDNAME = "loginResult";
    public static final String GRAPHQL_TOKEN_FIELDNAME = "token";
    public static final String GRAPHQL_FILTERRESULT_TYPENAME = "FilterResult";
    public static final String GRAPHQL_ISVALID_FIELDNAME = "isValid";
    public static final String GRAPHQL_HINTS_FIELDNAME = "hints";
    public static final String GRAPHQL_TESTRESULT_TYPENAME = "TestResult";
    public static final String GRAPHQL_ISAVALIABLE_FIELDNAME = "isAvaliable";
    public static final String GRAPHQL_INSERTRESULT_POSTFIX="InsertResult";
    public static final String GRAPHQL_UPDATERESULT_POSTFIX="UpdateResult";
    public static final String GRAPHQL_DELETERESULT_POSTFIX="DeleteResult";
    public static final String GRAPHQL_NESTINPUTRESULT_TYPENAME="NestInputResult";
    public static final String GRAPHQL_NESTINPUT_OBJECTID_FIELDNAME="inputNestIDList";
    public static final String GRAPHQL_NESTREMOVERESULT_TYPENAME="NestRemoveResult";
    public static final String GRAPHQL_NESTREMOVE_OBJECTID_FIELDNAME="removeNestIDList";
    public static final String GRAPHQL_NAME_FIELDNAME = "name";
    public static final String GRAPHQL_VALUES_FIELDNAME="values";
    public static final String GRAPHQL_HOST_FIELDNAME="host";
    public static final String GRAPHQL_PORT_FIELDNAME="port";
    public static final String GRAPHQL_DATABASENAME_FIELDNAME="databasename";
    public static final String GRAPHQL_CHARACTER_ENCODING_FIELDNAME="character_encoding";
    public static final String GRAPHQL_MAX_CONNECTION_FIELDNAME="maxConnection";
    public static final String GRAPHQL_MIN_CONNECTION_FIELDNAME="minConnection";
    public static final String GRAPHQL_MIN_IDLE_CONNECTION_FIELDNAME="minIdleConnection";
    public static final String GRAPHQL_MAX_IDLE_CONNECTION_FIELDNAME="maxIdleCconnection";
    public static final String GRAPHQL_CONNECTION_STR_FIELDNAME="connectionStr";
    public static final String GRAPHQL_REPLICA_NAME_FIELDNAME="replicaName";
    public static final String GRAPHQL_THREAD_FIELDNAME="thread";
    public static final String GRAPHQL_TRIGGER_TIME_FIELDNAME="triggerTime";
    public static final String GRAPHQL_IS_SUCCEED_FIELDNAME="isSucceed";
    public static final String GRAPHQL_COMMON_IDL_FIELDNAME="commonIDL";
    public static final String GRAPHQL_EVENTTYPE_FIELDNAME = "eventType";
    public static final String GRAPHQL_CONDITION_FIELDNAME = "condition";
    public static final String GRAPHQL_HEADERS_FIELDNAME = "headers";
    public static final String GRAPHQL_OK_STATUS_FIELDNAME = "okStatus";
    public static final String GRAPHQL_PAYLOAD_FIELDNAME="payload";
    public static final String GRAPHQL_PAYLOADFORMATTER_FIELDNAME="payloadFormatter";
    public static final String GRAPHQL_PAYLOADARGS_FIELDNAME="payloadargs";
    public static final String GRAPHQL_RETRY_TIMES_FIELDNAME="retryTimes";
    public static final String GRAPHQL_DESC_POSTFIX = "desc";
    public static final String GRAPHQL_ASC_POSTFIX = "asc";
    public static final String GRAPHQL_INLIST_POSTFIX = "InList";
    public static final String GRAPHQL_LISTMATCH_POSTFIX = "ListMatch";
    public static final String GRAPHQL_FIELDFILTER_POSTFIX = "FieldFilter";
    public static final String GRAPHQL_INPUT_POSTFIX = "Input";
    public static final String GRAPHQL_ADDINPUT_POSTFIX = "AddInput";
    public static final String GRAPHQL_NESTIDINPUT_POSTFIX = "IDInput";
    public static final String GRAPHQL_NESTOBJECTINPUT_POSTFIX = "ObjectInput";
    public static final String GRAPHQL_NESTREMOVE_POSTFIX="NestRemove";
    public static final String GRAPHQL_REMOVEINPUT_POSTFIX = "Remove";
    public static final String GRAPHQL_WHEREINPUT_POSTFIX = "WhereInput";
    public static final String GRAPHQL_UPDATEINPUT_POSTFIX = "UpdateInput";
    public static final String GRAPHQL_SUBSCRIPTION_NAME_PREFIX="change";
    public static final String GRAPHQL_WHERE_ARGUMENT = "where";
    public static final String GRAPHQL_SELECTFIELDS_FIELDNAME="select";
    public static final String GRAPHQL_WATCHFIELDS_FIELDNAME="watch";
    public static final String GRAPHQL_EXPIREDATE_FIELDNAME ="expiredate";
    public static final String GRAPHQL_STARTDATE_FIELDNAME="startdate";
    public static final String GRAPHQL_SELECTFIELDSMAP_INPUT_POSTFIX="FieldsMap";
    public static final String GRAPHQL_SELECTFIELDSMAP_METADATA="fieldsmap_metadata";
    public static final String GRAPHQL_SKIP_ARGUMENT = "skip";
    public static final String GRAPHQL_LIMIT_ARGUMENT = "limit";
    public static final String GRAPHQL_ORDERBY_ARGUMENT = "orderBy";
    public static final String GRAPHQL_FIRST_ARGUMENT = "first";
    public static final String GRAPHQL_LAST_ARGUMENT = "last";
    public static final String GRAPHQL_EVENT_ARGUMENT = "event";
    public static final String GRAPHQL_SUBSCRIPTION_ID_ARGUMENT="subscription_id";
    public static final String GRAPHQL_SESSION_ID_ARGUMENT="session_id";
    public static final String GRAPHQL_OBJECT_ARGUMENT = "object";
    public static final String GRAPHQL_OBJECTS_ARGUMENT = "objects";
    public static final String GRAPHQL_CONFLICT_ARGUMENT = "conflict";
    public static final String GRAPHQL_CONFLICT_TYPENAME="Conflict";
    public static final String GRAPHQL_EVENT_TYPENAME="Event";
    public static final String GRAPHQL_EVENT_INSERT="Insert";
    public static final String GRAPHQL_EVENT_DELETE="Delete";
    public static final String GRAPHQL_EVENT_UPDATE="Update";
    public static final String GRAPHQL_CONFLICT_ERROR="error";
    public static final String GRAPHQL_CONFLICT_REPLACE="replace";
    public static final String GRAPHQL_EVENTDATA_POSTFIX="eventData";
    public static final String GRAPHQL_FROM_ID ="fromId";
    public static final String GRAPHQL_TO_ID ="toId";
    public static final String GRAPHQL_TO_OBJECT ="toObject";
    public static final String GRAPHQL_CONTENTTYPE_TYPENAME = "ContentType";
    public static final String GRAPHQL_SCHEMA_TYPENAME = "Schema";
    public static final String GRAPHQL_CURRENTSCHEMA_FIELDNAME="currentSchema";
    public static final String GRAPHQL_PUBLISHEDSCHEMA_FIELDNAME="publishedSchema";
    public static final String GRAPHQL_PUBLISHEDHISTORY_FIELDNAME="publishedHistory";
    public static final String GRAPHQL_THIRD_API_FIELDNAME="thirdAPIs";
    public static final String GRAPHQL_INPUT_FIELDNAME="input";
    public static final String GRAPHQL_OUTPUT_FIELDNAME="output";
    public static final String GRAPHQL_ENDPOINT_FIELDNAME="endpoint";
    public static final String GRAPHQL_OBJECTTYPES_FIELDNAME="objectTypes";
    public static final String GRAPHQL_ENUMTYPES_FIELDNAME="enumTypes";
    public static final String GRAPHQL_RELATION_FIELDNAME="relations";
    public static final String GRAPHQL_SCHEMAROLE_FIELDNAME="schemaRoles";
    public static final String GRAPHQL_VERSIONID_FIELDNAME="versionid";
    public static final String GRAPHQL_SCHEMAOBJECT_FIELDNAME="schemaObject";
    public static final String GRAPHQL_PUBLISHEDSCHEMA_TYPENAME="SchemaMetaData";
    public static final String GRAPHQL_PUBLISHEDSCHEMAID_FIELDNAME="publishedSchema";
    public static final String GRAPHQL_SCHEMAID_FIELDNAME="schemaID";
    public static final String GRAPHQL_TYPENAME_FIELDNAME="typeName";
    public static final String GRAPHQL_USERTYPE_ID="usertype_id";
    public static final String GRAPHQL_THIRDAPI_TYPE_ID="thirdapis_id";
    public static final String GRAPHQL_THIRDAPI_TYPE_NAME="ThirdAPI";
    public static final String GRAPHQL_UNIQUECONSTRAINTS_TYPE_ID="uniqueconstraint_id";
    public static final String GRAPHQL_UNIQUECONSTRAINTS_TYPE_NAME="UniqueConstraint";
    public static final String GRAPHQL_ENUMTYPE_TYPE_ID="enumtype_id";
    public static final String GRAPHQL_ENUMTYPE_TYPENAME="EnumType";
    public static final String GRAPHQL_FROMRELATION_TYPENAME="FromRelation";
    public static final String GRAPHQL_TORELATION_TYPENAME="ToRelation";
    public static final String GRAPHQL_SCALARFIELD_TYPE_ID="sclarfield_id";
    public static final String GRAPHQL_SCALARFIELD_TYPENAME="ScalarField";
    public static final String GRAPHQL_ENUMFIELD_ID="enumfield_id";
    public static final String GRAPHQL_ENUMFIELD_NAME="EnumField";
    public static final String GRAPHQL_OPERATION_RESULT_NAME="OperationResult";
    public static final String GRAPHQL_USERLOGIN_APINAME="UserLogin";
    public static final String GRAPHQL_PASSWORDCHANGE_APINAME="PasswordChange";
    public static final String GRAPHQL_PASSWORDRESET_APINAME="PasswordReset";
    public static final String GRAPHQL_ADMIN_ID="admin_id";
    public static final String GRAPHQL_GUEST_ID="guest_id";
    public static final String GRAPHQL_VALUE_FIELDNAME="value";
    public static final String GRAPHQL_SCHEMAOBJECT_ID="schemaobject_id";
    public static final String GRAPHQL_CLASSNAME_FIELDNAME="classname";
    public static final String GRAPHQL_APINAME_FIELDNAME="apiname";
    public static final String GRAPHQL_ARGUMENTS_FIELDNAME="arguments";
    public static final String GRAPHQL_DISABLED_ROLES_FIELDNAME="disabledRoles";
    public static final String GRAPHQL_RETURN_TYPE_FIELDNAME="returnType";
    public static final String GRAPHQL_TRIGGER_TYPENAME = "Trigger";
    public static final String GRAPHQL_TRIGGER_HISTORY_TYPENAME="TriggerHistory";
    public static final String GRAPHQL_TRIGGER_FIELDNAME="trigger";
    public static final String GRAPHQL_TRIGGER_HISTORY_FIELDNAME="triggerHistory";
    public static final String GRAPHQL_SCHEMAPERMISSION_TYPENAME = "SchemaPermission";
    public static final String GRAPHQL_SCHEMAROLE_TYPENAME = "SchemaRole";
    public static final String GRAPHQL_SCHEMASTATUS_TYPENAME = "SchemaStatus";
    public static final String GRAPHQL_DATABASENAME_PREFIX="db_";
    public static final String GRAPHQL_SCHEMA_ID_DEFAULT = "schemadb";
    public static final String GRAPHQL_SCHEMANAME_DEFAULT="easygql_engine";
    public static final String GRAPHQL_LOGINEDUSER_OBJECTNAME = "loginedUser";
    public static final String GRAPHQL_LongFILTER_TYPENAME = "LongFilter";
    public static final String GRAPHQL_BigDecimalFILTER_TYPENAME = "BigDecimalFilter";
    public static final String GRAPHQL_BOOLEANFILTER_TYPENAME = "BoolFilter";
    public static final String GRAPHQL_ENUMFILTER_TYPENAME = "EnumFilter";
    public static final String GRAPHQL_INTLISTWHEREINPUT = "IntListWhereInput";
    public static final String GRAPHQL_USERCreate_APINAME="UserCreate";
    public static final String GRAPHQL_ROLEPROMOTED_APINAME="RolePromoted";
    public static final String GRAPHQL_LONGLISTWHEREINPUT = "LongListWhereInput";
    public static final String GRAPHQL_SHORTLISTWHEREINPUT = "ShortListWhereInput";
    public static final String GRAPHQL_BYTELISTWHEREINPUT = "ByteListWhereInput";
    public static final String GRAPHQL_BIGDECIMALLISTWHEREINPUT = "BigDecimalListWhereInput";
    public static final String GRAPHQL_StringLISTWHEREINPUT = "StringListWhereInput";
    public static final String GRAPHQL_IDLISTWHEREINPUT = "IDListWhereInput";
    public static final String GRAPHQL_FLOATLISTWHEREINPUT = "FloatListWhereInput";
    public static final String GRAPHQL_DOUBLELISTWHEREINPUT = "DoubleListWhereInput";
    public static final String GRAPHQL_THIRDAPI_OUTPUT_POSTFIX="ThirdOutput";
    public static final String GRAPHQL_API_RESULT_POSTFIX ="APIResult";
    public static final String GRAPHQL_DATA_RESULT_FIELDNAME="data";
    public static final String SUBSCRIPTION_TYPE_ALL = "all";
    public static final String GRAPHQL_ACTION_FIELDNAME="action";
    public static final String SUBSCRIPTION_TYPE_INSERT = "insert";
    public static final String SUBSCRIPTION_TYPE_REMOVE = "delete";
    public static final String SUBSCRIPTION_TYPE_UPDATE = "update";
    public static final String SUBSCRIPTION_ACTION="action";
    public static final String GRAPHQL_SUBSCRIPTION_NODE_TYPE="ChangeNode";
    public static final String SUBSCRIPTION_NODE_OLD="oldVal";
    public static final String SUBSCRIPTION_NODE_NEW="newVal";
    public static final String TRIGGER_DEFAULT_OK_STATUS="200";
    public static final Integer TRIGGER_DEFAULT_RETRY_TIMES=3;
    public static final String SCHEMA_STATUS_UNINITIALIZED = "uninitialized";
    public static final String GRAPHQL_UNIQUE_CONSTRAINT_POSTFIX="unique_key";
    public static final String SCHEMA_STATUS_STARTTING = "starting";
    public static final String SCHEMA_STATUS_RUNNING = "running";
    public static final String SCHEMA_STATUS_STOPPING = "stopping";
    public static final String SCHEMA_STATUS_STOPPED = "stopped";
    public  static final String GRAPHQL_SCHEMASTATUS_FIELDNAME="status";
    public static final String RELATIONTYPE_ADDNEWOBJECT = "AddNewObject";
    public static final String RELATIONTYPE_ADDIDRELATION = "AddIDRelation";
    public static final String RELATIONTYPE_REPLACENEWOBJECT = "ReplaceNewObject";
    public static final String RELATIONTYPE_REPLACEIDRELATION = "ReplaceIDRelation";
    public static final String GRAPHQL_THIRDAPI_METADATA_DIRECTIVE="thirdapi_metadata";
    public static final String GRAPHQL_SELECTBYID_METADATA_DIRECTIVE="selectbyid_metadata";
    public static final String GRAPHQL_SELECTBYID_POSTFIX="ByID";
    public static final String GRAPHQL_SELECTBYCONDITION_POSTFIX="ByCondition";
    public static final String GRAPHQL_DESTORY_POSTFIX="Destory";
    public static final String GRAPHQL_SELECTBYCONDITION_METADATA_DIRECTIVE="selectbycondition_metadata";
    public static final String GRAPHQL_ENUMFILTER_METADATA="enumfilter_metadata";
    public static final String GRAPHQL_ENUMLISTFILTER_METADATA="enumlistfilter_metadata";
    public static final String GRAPHQL_SUBSCRIPTION_METADATA="subscription_metadata";
    public static final String SUBSCRIPTION_NODE_METADATA="subscription_node_metadata";
    public static final String GRAPHQL_API_OBJECTUPDATE_DIRECTIVE="objectupdate_api";
    public static final String GRAPHQL_WEBHOOK_URL_FIELDNAME="webhookurl";
    public static final String GRAPHQL_TRIGGER_CHANNEL_POSTFIX="channel_";
    public static final String GRAPHQL_TRIGGER_NAME_PREFIX="trigger_";
    public static final String GRAPHQL_API_OBJECTDESTORY_DIRECTIVE="objectdestory_api";
    public static final String GRAPHQL_API_OBJECTCREATE_DIRECTIVE="objectcreate_api";
    public static final String GRAPHQL_API_FIELD_IN_CONTENTTYPE_ADD="field_in_contenttype_add";
    public static final String GRAPHQL_API_FIELD_IN_CONTENTTYPE_REMOVE="field_in_contenttype_remove";
    public static final String GRAPHQL_OBJECT_METADATA_DIRECTIVE="object_metadata";
    public static final String GRAPHQL_OBJECTINPUT_METADATA_DIRECTIVE="objectinput_metadata";
    public static final String GRAPHQL_OBJECTUPDATEINPUT_METADATA_DIRECTIVE="objectupdateinput_metadata";
    public static final String GRAPHQL_OBJECTWHEREINPUT_METADATA_DIRECTIVE="objectwhereinput_metadata";
    public static final String GRAPHQL_OBJECTFIELDFILTER_METADATA_DIRECTIVE="objectfieldfilter_metadata";
    public static final String GRAPHQL_NODES_FIELDNAME="nodes";
    public static final String GRAPHQL_INSERTRESULT_METADATA_DIRECTIVE="insertresult_metadata";
    public static final String GRAPHQL_UPDATERESULT_METADATA_DIRECTIVE="updateresult_metadata";
    public static final String GRAPHQL_DELETERESULT_METADATA_DIRECTIVE="delteresult_metadata";
    public static final String GRAPHQL_LOGINRESULT_METADATA_DIRECTIVE="loginresult_metadata";
    public static final String GRAPHQL_FIELDMETADATA_DIRECTIVE="fieldmetadata";
    public static final String GRAPHQL_NESTFROMOBJECTINPUT_DIRECTIVE="nest_fromobjectinput_metadata";
    public static final String GRAPHQL_NESTFROMIDINPUT_DIRECTIVE="nest_fromidinput_metadata";
    public static final String GRAPHQL_NESTTOIDINPUT_DIRECTIVE="nest_toidinput_metadata";
    public static final String GRAPHQL_NESTFROMREMOVE_DIRECTIVE="nest_fromremove_metadata";
    public static final String GRAPHQL_NESTTOREMOVE_DIRECTIVE="nest_toremove_metadata";
    public static final String GRAPHQL_SCHEMAMETADATA="schemadata";
    public static final String GRAPHQL_DIRECTIVE_METADATA="metadata";
    public static final String GRAPHQL_FIELDNAME_FIELDNAME="fieldName";
    public static final String GRAPHQL_OBJECTNAME_FIELDNAME="objectName";
    public static final String GRAPHQL_ENUMNAME_FILEDNAME="enumName";
    public static final Integer GRAPHQL_ONE_TO_ONE_VALUE=1;
    public static final Integer GRAPHQL_ONE_TO_MANY_VALUE=2;
    public static final Integer GRAPHQL_MANY_TO_MANY_VALUE=3;
    public static final String EVENTTYPE_INSERT = "insert";
    public static final String EVENTTYPE_REMOVE = "remove";
    public static final String EVENTTYPE_UPDATE = "update";
    public static final String EVENTTYPE_ALL = "all";
    public static final String CONFLICTSTRATEGY_REPLACE = "replace";
    public static final String CONFLICTSTRATEGY_UPDATE = "update";
    public static final String CONFLICTSTRATEGY_ERROR = "error";
    public static final String VALUETYPE_NEWVALUE = "newValue";
    public static final String VALUETYPE_OLDVALUE = "oldValue";
    public static final String VALUETYPE_BOTH = "both";
    public static final String FIELDATTR_SCALARTYPE = "scalartype";
    public static final String FIELDATTR_REFERENCE = "reference";
    public static final String ROLE_ADMIN = "Admin";
    public static final String ROLE_GUEST = "Guest";
    public static final String ROLE_DEFAULT="Default";
    public static final String MANY_POSTFIX="Many";
    public static final String CREATE_POSTFIX="Create";
    public static final String DESTROY_POSTFIX="Destroy";
    public static final String UPDATE_POSTFIX="Update";
    public static final String SUBSCRIPTION_POSTFIX="Listener";
    public static final String FIELD_LIST_POSTFIX="list";
    public static final String FIELD_ID_LIST_POSTFIX="IDList";
    public static final String FIELD_WORD_SEPERATOR="_";
    public static final String GRAPHQL_ENUM_FILTER_POSTFIX="EnumFilter";
    public static final String GRAPHQL_ENUM_LISTFILTER_POSTFIX="EnumListFilter";
    public static final String GRAPHQL_ENUM_POSTFIX="Enum";
    public static final DecimalFormat GRAPHQL_VERSION_ID_FORMAT= new DecimalFormat("00000000");
    public static final DecimalFormat GRAPHQL_ENUM_SEQUNCE_FORMAT=new DecimalFormat("0000");
    public static final String GRAPHQL_UNIQUE_FIELDS_DIRECTIVE="uniqueFields";
    public static final String GRAPHQL_API_KIND_INSERT="INSERT";
    public static final String GRAPHQL_API_KIND_DELETE="DELETE";
    public static final String GRAPHQL_API_KIND_QUERYONE="SELECT_BY_ID";
    public static final String GRAPHQL_API_KIND_QUERYMANY="SELECT_BY_CONDITION";
    public static final String GRAPHQL_API_KIND_UPDATE="UPDATE";
    public static final String GRAPHQL_API_KIND_SUBSCRIPTION="SUBSCRIPTION";
    public static final String GRAPHQL_API_KIND_THIRDAPI="THIRDAPI";
    public static final String GRAPHQL_API_KIND_NESTFIELD_IDINPUT="NESTFIELD_IDINPUT";
    public static final String GRAPHQL_API_KIND_NESTFIELD_OBJECTINPUT="NESTFIELD_OBJECTINPUT";
    public static final String GRAPHQL_API_KIND_NESTFIELD_REMOVE="NESTFIELD_REMOVE";
    public static final String GRAPHQL_TABLE_SQL="tablesql";
    public static final String GRAPHQL_CONSTRAINT_SQL="constraintsql";
    public static final String GRAPHQL_FOREIGN_KEY_POSTFIX="_fk";
    public static final String LANG_ZH="zh_CN";
    public static final String LANG_EN="en_US";



    /**
     * @throws InternalServerException
     */
    public ConfigurationProperties() {
        Properties env = loadConfig();
        POSTGRES_IP = Optional.ofNullable(env.getProperty("POSTGRES_IP")).orElse("127.0.0.1");
        POSTGRES_PORT = Integer.parseInt(Optional.ofNullable(env.getProperty("POSTGRES_PORT")).orElse("5432"));
        POSTGRES_DATABASENAME = Optional.ofNullable(env.getProperty("POSTGRES_DATABASENAME")).orElse("postgres");
        POSTGRES_USER = Optional.ofNullable(env.getProperty("POSTGRES_USER")).orElse("postgres");
        POSTGRES_PASS = Optional.ofNullable(env.getProperty("POSTGRES_PASS")).orElse("password");
        POSTGRES_MAX_CONNECTIONS = Integer.parseInt(Optional.ofNullable(env.getProperty("POSTGRES_MAX_CONNECTIONS")).orElse("1000"));
        POSTGRES_MAX_IDLE_CONNECTIONS = Integer.parseInt(Optional.ofNullable(env.getProperty("POSTGRES_MAX_IDLE_CONNECTIONS")).orElse("10"));
        POSTGRES_DATASOURCE_INSTANCE = DataSourceInfo.builder().host(POSTGRES_IP).port(POSTGRES_PORT).databasename(POSTGRES_DATABASENAME).username(POSTGRES_USER).password(POSTGRES_PASS).max_connection(POSTGRES_MAX_CONNECTIONS).max_idle_connection(POSTGRES_MAX_IDLE_CONNECTIONS).build();
        SCHEMAID_DEFAULT = Optional.ofNullable(env.getProperty("SCHEMAID_DEFAULT")).orElse("schemadb");
        DEFAULT_TIME_FORMAT = DateTimeFormatter.ofPattern(Optional.ofNullable(env.getProperty("DEFAULT_TIME_FORMAT")).orElse("HH:mm:ss"));
        DEFAULT_DATE_FORMAT = DateTimeFormatter.ofPattern(Optional.ofNullable(env.getProperty("DEFAULT_DATE_FORMAT")).orElse("yyyyMMdd"));
        DEFAULT_DATETIME_FORMAT = DateTimeFormatter.ofPattern(Optional.ofNullable(env.getProperty("DEFAULT_DATE_FORMAT")).orElse("yyyyMMdd HH:mm:ss"));
        ROLE_IN_USER_FIELDNAME = Optional.ofNullable(env.getProperty("ROLE_IN_USER_FIELDNAME")).orElse("role");
        GRAPHQL_RECURSIVE_DEEPTH = Integer.valueOf(Optional.ofNullable(env.getProperty("GRAPHQL_RECURSIVE_DEEPTH")).orElse("5"));
        SCHEMA_DATABASE_KIND = Optional.ofNullable(env.getProperty("SCHEMA_DATABASE_KIND")).orElse(DATABASE_KIND_POSTGRES);
        String languageStr = Optional.ofNullable(env.getProperty("EASYGQL_LANGUAGE")).orElse(LANG_EN);
        String[] languageArray=languageStr.split("_");
        Locale.setDefault(new Locale("en","US"));
        if(languageArray.length==0) {
            GRAPHQL_LANG=new Locale("en","US");
        }  else if(languageArray.length==1) {
            GRAPHQL_LANG=new Locale(languageArray[0]);
        } else if(languageArray.length==2) {
            GRAPHQL_LANG=new Locale(languageArray[0],languageArray[1]);
        } else if(languageArray.length==3) {
            GRAPHQL_LANG=new Locale(languageArray[0],languageArray[1],languageArray[2]);
        } else {
            GRAPHQL_LANG=new Locale("en","US");
        }
    }
    public static ConfigurationProperties getInstance() {
        return  instance;
    }
    public static void reload() {
        instance = new ConfigurationProperties();
    }

    /**
     * @return
     * @throws InternalServerException
     */


    private static Properties loadConfig() {
           Properties properties = null;
            try {
                properties = PropertiesLoaderUtils.loadAllProperties(property);
            } catch (IOException e) {
                e.printStackTrace();
            }
        return properties;
    }
}
